language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --all -- --test-threads 1
  - cargo test --verbose --all -- --test-threads 1
